"""Render the cohort analysis as a Markdown report.

WHY a fixed layout: the report is the artefact that gets committed, hashed and
cited. Its order mirrors the pre-registration: the registered outcome sentence
first, then the fixed sequence step by step (with the alpha-carrying status of
each line stated), then everything descriptive under a heading that says so.
"""

from __future__ import annotations

from typing import Any


def pct(x: float | None, signed: bool = False) -> str:
    if x is None:
        return "n/a"
    return f"{x * 100:+.1f} pts" if signed else f"{x * 100:.1f}%"


def num(x: Any, digits: int = 4) -> str:
    if x is None:
        return "n/a"
    if isinstance(x, float):
        return f"{x:.{digits}g}"
    return str(x)


def render(rep: dict[str, Any]) -> str:
    h, c, st = rep["header"], rep["cohort"], rep["steps"]
    L: list[str] = []
    L.append("# DailyVox K-curve study: cohort report")
    L.append("")
    if h.get("synthetic"):
        L.append("> **SYNTHETIC DATA.** Every participant in this report is generated by "
                 "`dailyvox-study synth`. Nothing here is a finding about people.")
        L.append("")
    L.append(f"- tool version: `{h['tool_version']}`")
    L.append(f"- protocol hash: `{h['protocol_hash']}`")
    L.append(f"- embedding model: `{h['embedding_model']}`")
    L.append(f"- generic head SHA-256: `{h['generic_head_sha256']}`")
    L.append(f"- result files: {c['files']} (status: {c['status']}); P0 excluded: "
             f"{', '.join(h['p0_excluded']) or 'none'}")
    L.append(f"- cohort counts: N_c = {c['N_c']}, N10 = {c['N10']}, **N25 = {c['N25']}**, "
             f"under-30 dropouts = {c['excluded_under_30']}")
    dis = rep["disagreement"]
    L.append(f"- label-free disagreement d at K=25, cohort median by lambda: "
             f"{dis['median_d_by_lambda']}; active lambda = {dis['active_lambda']:g}"
             f"{' (switched to the registered fallback, section 6.6)' if dis['lambda_switched_to_fallback'] else ''}"
             f"; low-d branch: {'YES' if dis['low_d_branch'] else 'no'}")
    L.append("")

    cl = rep["claim"]
    L.append("## Registered outcome sentence (prereg section 6.4)")
    L.append("")
    L.append(f"Claim-map row **{cl['row']}**:")
    L.append("")
    L.append(f"> {cl['headline']}")
    L.append("")
    for q in cl["qualifiers"]:
        L.append(f"- {q}")
    for n in cl["notes"]:
        L.append(f"- Note: {n}")
    L.append("")

    L.append("## Fixed sequence (alpha = 0.05, one-sided, stops at first non-rejection)")
    L.append("")
    L.append("| Step | Test | Outcome | Carries alpha |")
    L.append("|---|---|---|---|")
    for s in st["sequence"]:
        L.append(f"| {s['step']} | {s['test']} | {s['outcome']} | {'yes' if s['carries_alpha'] else 'no'} |")
    L.append("")
    s1 = st["step1"]
    L.append(f"**Step 1 (H1).** mean Delta-acc(K=25) = {pct(s1.get('mean_delta'), True)}; "
             f"sign-flip p = {num(s1.get('p'))} ({s1.get('method')}); N25 = {s1.get('n')}, "
             f"exact ties = {s1.get('ties')}, N_eff = {s1.get('n_eff')}, "
             f"attainable floor 2^-N_eff = {num(s1.get('p_floor'))}.")
    L.append("")
    b = st["step1b"]
    L.append(f"**Step 1b.** Fisher-combined one-sided McNemar p = {num(b.get('p'))} "
             f"({b.get('note', '')}); participants with b = c = 0 (undefined): "
             f"{b.get('undefined_b_eq_c_eq_0')}.")
    if b.get("per_user_p"):
        L.append("")
        L.append("| participant | McNemar p | Fisher p leaving this one out |")
        L.append("|---|---|---|")
        for code, p in b["per_user_p"].items():
            L.append(f"| {code} | {num(p)} | {num(b['leave_one_out_p'].get(code))} |")
    L.append("")
    s2 = st["step2"]
    L.append(f"**Step 2 (H2).** wins {s2['wins']} / ties {s2['ties']} / losses {s2['losses']} "
             f"of N25 = {s2['n25']} (ties count as losses); k*(N25) = {num(s2['k_star'])}; "
             f"exact binomial p = {num(s2['exact_p'])}; {'PASS' if s2['pass'] else 'miss'}.")
    s3 = st["step3"]
    L.append(f"**Step 3 (H3).** personalized minus prior-only: mean {pct(s3.get('mean_delta'), True)}, "
             f"sign-flip p = {num(s3.get('p'))}, ties = {s3.get('ties')}, "
             f"N_eff(H3) = {s3.get('n_eff')}.")
    L.append(f"**Step 4 (H3b).** {st['step4']['verdict']}: {st['step4']['reason']}.")
    s5 = st["step5"]
    L.append(f"**Step 5 (H4).** K=10 wins {s5['wins']} / ties {s5['ties']} / losses {s5['losses']} "
             f"of N10 = {s5['n10']}; k*(N10) = {num(s5['k_star'])}; exact p = {num(s5['exact_p'])}. "
             "Carries alpha only if Steps 1-4 all rejected, which cannot happen while Step 4 is "
             "unrunnable.")
    L.append("")
    comp = rep["compound"]
    L.append(f"**Compound win (section 3.2, description only).** {comp['wins']} of {comp['n25']}"
             + (f"; k* = {comp['k_star']}, exact p = {num(comp['exact_p_description_only'])} "
                "(description only, carries no alpha)" if "k_star" in comp
                else f"; {comp['threshold']}") + ".")
    inf = rep["inferiority"]
    L.append(f"**Inferiority criterion (section 6.3).** Clopper-Pearson upper 95% bound on win "
             f"probability = {num(inf['clopper_pearson_upper'])} (fires below 0.70); bootstrap "
             f"upper 95% bound on mean Delta = {pct(inf['bootstrap_upper_mean_delta'], True)} "
             f"(fires below +6 pts); met: {inf['met']}.")
    sc = rep["sub_chance"]
    L.append(f"**Sub-chance check (row 12).** generic head below its empirical-chance threshold "
             f"for {sc['n_generic_below_empirical_chance']} of N25; cohort mean generic accuracy "
             f"{pct(sc['mean_acc_generic'])} vs mean majority-of-pool {pct(sc['mean_acc_majority_of_pool'])}; "
             f"triggered: {sc['triggered']}.")
    L.append("")

    L.append("## Permutation-null diagnostic (section 7.5, never displaces the primary)")
    L.append("")
    nl = rep["null"]
    if nl:
        L.append(f"- mean null Delta-acc(K=25) over {nl['n_permutations']} within-user shuffles: "
                 f"{pct(nl['mean_null_delta_primary_over_permutations'], True)} "
                 f"(first shuffle: {pct(nl['mean_null_delta_primary_first_permutation'], True)})")
        L.append(f"- mean prior-only Delta-acc(K=25): {pct(nl['mean_prior_only_delta_primary'], True)} "
                 "(health check on real data: null should be close to prior-only; on uniform "
                 "synthetic labels both should be close to 0)")
        L.append(f"- null win-rate (mean over shuffles): {pct(nl['null_win_rate_mean'])}; observed "
                 f"win count {nl['observed_win_count']} beats {pct(nl['observed_win_percentile_vs_null'])} "
                 "of null cohorts")
    L.append("")

    L.append("## Descriptive tier (no p-value here is interpreted)")
    L.append("")
    d = rep["descriptive"]
    L.append("**S1/S9 K-curve** (Delta-acc vs generic; one-sided 90% lower bounds, percentile and BCa):")
    L.append("")
    L.append("| K | eligible N | mean Delta | W/T/L | percentile lower | BCa lower |")
    L.append("|---|---|---|---|---|---|")
    for k, e in d["curve"].items():
        iv = e.get("interval_90", {})
        L.append(f"| {k[1:]} | {e['eligible_n']} | {pct(e['mean_delta'], True)} | "
                 f"{e['wins']}/{e['ties']}/{e['losses']} | {pct(iv.get('percentile_lower'), True)} | "
                 f"{pct(iv.get('bca_lower'), True)} |")
    kh = d["k_half"]
    L.append("")
    if kh["value"] is None:
        L.append("K_half: not defined (no positive K=25 lift to halve).")
    else:
        share = kh["bootstrap_histogram"].get(str(kh["value"]), 0) / max(
            sum(kh["bootstrap_histogram"].values()), 1)
        L.append(f"Half of the K=25 lift was already present at K = {kh['value']} "
                 f"(bootstrap: {share * 100:.0f}% of resamples).")
    L.append("")
    L.append("**S4 win/tie/loss of the personalized head vs each comparator:**")
    L.append("")
    L.append("| K | vs generic | vs prior-only | vs recency last-K |")
    L.append("|---|---|---|---|")
    for k, row in d["wtl_by_comparator"].items():
        f = lambda w: f"{w['wins']}/{w['ties']}/{w['losses']}"
        L.append(f"| {k[1:]} | {f(row['vs_generic'])} | {f(row['vs_prior_only'])} | "
                 f"{f(row['vs_recency_last_k'])} |")
    L.append("")
    L.append("Donor, donorPlusPrior and pooledLOPO: n/a in the result-file-only design (DEVIATIONS D4).")
    L.append("")
    rec = rep["recency"]
    L.append(f"**Section 7.7 recency arm.** mean first-K minus last-K: K=5 "
             f"{pct(rec['k5']['mean_first_minus_last'], True)}, K=10 "
             f"{pct(rec['k10']['mean_first_minus_last'], True)}; last-K >= first-K at both: "
             f"{rec['last_k_ge_first_k_at_5_and_10']}.")
    L.append("")
    refs = d["reference_lines_mean_n25"]
    L.append("**Reference lines (N25 means):** " + "; ".join(
        f"{k} {pct(v)}" for k, v in refs.items())
        + ". persistence-full CONSUMES earlier test-window gold labels (oracle-flavoured).")
    L.append("")
    L.append(f"**S7 empirical chance by test size:** {d['empirical_chance_by_m']}")
    L.append(f"**S2 macro-F1 means:** {fmt_map(d['macro_f1_mean'])}")
    L.append(f"**S3 neutral recall means:** {fmt_map(d['neutral_recall_mean'])}; "
             f"**collapse rate means:** {fmt_map(d['collapse_rate_mean'])}")
    L.append(f"**S5 prior-drift TV means:** {fmt_map(d['prior_drift_tv_mean'])}")
    L.append("**S10 labelling (pool vs test):** " + "; ".join(
        f"{w}: {fmt_map(v)}" for w, v in d["labelling"].items()))
    L.append(f"**S12 gap@25 per participant:** {d['gap_primary']}")
    L.append(f"**F12 solver failures:** {d['solver_failures']} of {d['solver_attempts']} refits")
    L.append("")
    L.append("**E5 lambda sweep, mean Delta-acc(K=25). POST-HOC, NOT CLAIM-BEARING:** "
             + fmt_map(d["lambda_sweep_post_hoc"], signed=True))
    L.append("")

    L.append("## Sensitivity analyses (section 3.4 directional rule applies)")
    L.append("")
    for name, s in rep["sensitivity"].items():
        if isinstance(s, dict):
            L.append(f"- {name}: n = {s.get('n')}, mean = {num(s.get('mean'))}, "
                     f"sign-flip p = {num(s.get('p'))}")
    L.append(f"- {rep['sensitivity']['directional_rule']}")
    L.append("")

    L.append("## Per-platform breakdown (descriptive)")
    L.append("")
    L.append("| platform | files | N25 | N10 | typed share | mean acc generic | mean acc K=25 | mean Delta | W/T/L |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for plat, p in rep["platforms"].items():
        if plat == "all":
            continue
        L.append(f"| {plat} | {p['files']} | {p['N25']} | {p['N10']} | {pct(p['typed_share'])} | "
                 f"{pct(p['mean_acc_generic'])} | {pct(p['mean_acc_k25'])} | "
                 f"{pct(p['mean_delta_primary'], True)} | {p['wins']}/{p['ties']}/{p['losses']} |")
    a = rep["platforms"]["all"]
    L.append("")
    L.append(f"Overall typed share {pct(a['typed_share'])}, voice share {pct(a['voice_share'])}; "
             f"per-person typed share min/median/max {pct(a['per_person_typed_share_min'])} / "
             f"{pct(a['per_person_typed_share_median'])} / {pct(a['per_person_typed_share_max'])}"
             + (f"; correlation of typed share with Delta (descriptive): "
                f"{num(a.get('corr_typed_share_vs_delta'), 3)}" if "corr_typed_share_vs_delta" in a else "")
             + ".")
    L.append("")
    return "\n".join(L) + "\n"


def fmt_map(m: dict[str, Any], signed: bool = False) -> str:
    return ", ".join(f"{k} {pct(v, signed) if signed else num(v, 3)}" for k, v in m.items())
